name: Build ebook

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "12.18.2"

      - name: Update system packages
        run: sudo apt update

      - name: Install dependencies
        run: sudo apt install libegl1 libopengl0 libxcb-cursor-dev

      - name: Install Calibre ebook tool
        run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Install gitbook-cli
        run: sudo npm install -g gitbook-cli

      - name: Install Gitbook plugins
        run: gitbook install

      - name: Create output directory
        run: mkdir output

      - name: Generate PDF
        run: gitbook pdf . ./output/typescript-book-${{ env.SHA }}.pdf

      - name: Generate EPUB
        run: gitbook epub . ./output/typescript-book-${{ env.SHA }}.epub

      - name: Generate MOBI
        run: gitbook mobi . ./output/typescript-book-${{ env.SHA }}.mobi

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-book.pdf
          path: ./output/typescript-book-${{ env.SHA }}.pdf

      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-book.epub
          path: ./output/typescript-book-${{ env.SHA }}.epub

      - name: Upload MOBI artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-book.mobi
          path: ./output/typescript-book-${{ env.SHA }}.mobi
